name: "🧰 Chore"
description: Tooling, CI/CD, dependencies, infra
title: "[CHORE] <subject>"
labels: ["chore"]
body:
  - type: textarea
    id: scope
    attributes:
      label: Scope
      placeholder: "CI pipeline, ESLint/Prettier, semantic-release, Render config"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      options:
        - label: No behavior change
          required: true
        - label: Requires doc update
  - type: markdown
    attributes:
      value: |
        ---
        💡 **Pro tip:** After creating this issue, comment  
        ```
        /branch
        ```
        or  
        ```
        /branch feat|bug|chore|docs|refactor
        ```
        to auto-create a properly named branch like `feat/123-add-user-login`.
