name: "❓ Question / Support"
description: Ask a question or request guidance
title: "[QUESTION] <topic>"
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Be specific; include context or links
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      placeholder: "What you tried, logs, screenshots"
