[tool.ruff]
line-length = 100
target-version = "py311"
lint.select = ["E","F","I","B","UP"]
exclude = ["venv",".venv","__pycache__","build","dist"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict_optional = true
warn_unused_ignores = true