name: Release
on:
  push:
    branches: [main, develop]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SEMANTIC_DEPLOY_KEY }}

      - name: Add GitHub to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set Git remote to SSH
        run: git remote set-url origin git@github.com:SanchitB23/remote-job-radar.git

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npx semantic-release
