name: Semantic PR Title

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  semantic-pr:
    name: PR title must be semantic
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.SEMREL_PAT }}
        with:
          ignoreLabels: |
            dependencies
          subjectPattern: "^[a-z].+"
          subjectPatternError: "Start the subject lowercase and be descriptive, e.g. 'feat: add job aggregator API endpoint'"
          types: |
            feat
            fix
            perf
            docs
            refactor
            test
            build
            ci
            chore
            release
